sudo: false

language: ruby
rvm:
  - 2.1

install:
   - bundle install
   - gem install html-proofer
script:
  - bundle exec jekyll build
  - htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
