# Jekyll
gems:
  - jekyll-redirect-from

# Custom
siteTitle: Corgi
siteDescription: My awesome personal site, i'm a Corgi!
avatar: /img/avatar.jpg
background: /img/background.jpg
description: Hey I'm a Corgi. Thanks for visiting my personal site!
resumeFile: https://dl.dropboxusercontent.com/u/3848960/corgi.pdf

icons:
  - icon: page
    link: resume.html
  - icon: social-github
    link: http://www.github.com/DDuarte
  - icon: social-twitter
    link: https://twitter.com/OhMyCorgi
  - icon: paw
    link: http://lmgtfy.com/?q=corgi
  - icon: social-reddit
    link: https://www.reddit.com/r/corgi

projects:
  - title: Jekyll Configurable Site
    link: https://github.com/DDuarte/JekyllConfigurablePersonalSite
